- name: stat the /tmp dir
  hosts: servera.lab.example.com
  gather_facts: false

  tasks:
    #- name: stat /tmp
    # stat:
    # path: /tmp
    # register: stat_output

    - name: show /tmp listing
      command: ls -l /tmp
      register: ls_output
      changed _when: false
      failed_when: "'‘flag' in ls_output.stdout"

    - name: show stat_output variable
      debug:
        var: ls_output
